#----------------------------------------------------------------------------
# This is the config file for the plugin.
#----------------------------------------------------------------------------

#----------------------------------------
# These maps will be the maps that
# are used in the game, if no host is
# online, the game will give the players
# the ability to vote for a map.
# The format is:
#   - map-name:map-size (Radius -> Blocks)
#----------------------------------------
game-maps:
  - 0000map1:2048

#----------------------------------------
# This is the map that will be used as
# the lobby
#----------------------------------------
lobby-map: 0000lobby
