#--------------------------------------------------------------
# This is the configuration file for the PlayerStatsAPI plugin.
# When it is asked for a plugin, you need to provide the full
# id of the plugin. (found when it is being enabled)
#--------------------------------------------------------------

#------------------------------------------------------
# These are the names of the plugins that are allowed
# to change every stat of a player.
# These don't have to be listed below. Except for the
# plugin.full-database-access.
# (Security Reasons)
#------------------------------------------------------
plugin.full-access:
  - "SillyUHC"

#------------------------------------------------------
# These are the names of the plugins that are allowed
# to change the coins of a player.
#------------------------------------------------------
plugin.coin-change:
  -

#------------------------------------------------------
# These are the names of the plugins that are allowed
# to change the all of Kill / Death / Wins / Loses of
# a player.
#------------------------------------------------------
plugin.kdwl-change:
  -

#------------------------------------------------------
# These are the names of the plugins that are allowed
# to change how far the daily playing streak of a
# player is.
#------------------------------------------------------
plugin.daily-change:
  -

#------------------------------------------------------
# These are the names of the plugins that are allowed
# to access the full database. (Not Recommended)
#------------------------------------------------------
plugin.full-database-access:
  -


#------------------------------------------------------
# These are the Database settings.
# database.host: The host (IP or URL) of the database.
# database.port: The port of the database.
# database.database: The name of the database.
# database.username: The username of the database.
# database.password: The password of the database.
# database.submit.on.change: If the plugin should submit
#                            the data to the database
#                            when it is changed.
#------------------------------------------------------
database.host: "localhost"
database.port: 3306
database.database: "playerstats"
database.username: "root"
database.password: "password"
database.submit.on.change: false
